### ISSUE TITLE
App Settings

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#19]
The current settings should be adapted to look and function more like @alexandradm's [mockups](https://projects.invisionapp.com/share/VPBXQBIK2#/screens/233813834).

![screen shot 2017-06-29 at 4 10 19 pm](https://user-images.githubusercontent.com/33829/27708273-5f74c580-5ce6-11e7-9bf0-08082375c24b.png)

I think that the user management piece can wait till a later iteration but for now it should allow you to do a sequence of things:

1. set app title
2. set app logo
3. set Twitter consumer key and consumer secret 
4. login with twitter
5. set app-wide locations

3-5 are the most important things to do for now. And they can only be done in sequence: you can't set locations until the user has logged in and you have their API access keys, and they can't login until the application keys have been set. So it's actually kind of complicated :-)

**Comment by raffazizzi** [comment]
@edsu I've made some changes to the authentication flow, just in my branch:

* if keys are not set, the app will show the home page, not the key settings page. This is because a non-setup user should still be able to land on the default home page as set by the admin (ie with instance location trends)
* if keys are not set, login will bring to the key settings page. The save button now also attempts to login
* to update keys users will (eventually, not yet) be able to do that from their profile page

The last point makes me think that "settings" (for now, just the keys) should actually be properties of the user rather than an app-wide setting. Although the server-side component will need **just one** set of keys to keep monitoring locations (and other operations), not one for each user. So who should set those keys? The admin? Do, in fact, other users need an application key to just log-in?

**Comment by edsu** [comment]
This all sounds good. 

The `CONSUMER_KEY` and `CONSUMER_SECRET` key pair identifies the DocNow application. Each user will need to have `an ACCESS_TOKEN` and `ACCESS_TOKEN_SECRET` key pair so that the application can collect data on their behalf (using their quota).

I'm definitely open to ideas for where to store these keys and how to make them available from the API as long as those constraints hold.
